// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjh07wepd6iGXW-QZy9UqJMBZQKzakHXw',
    appId: '1:857670497949:web:d8c311205bf468fe9c8674',
    messagingSenderId: '857670497949',
    projectId: 'template-dev-d032e',
    authDomain: 'template-dev-d032e.firebaseapp.com',
    storageBucket: 'template-dev-d032e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzUtDJxSjKo5CAonO7ZkpZ3rKW31UhUg',
    appId: '1:857670497949:android:94ac8764c3b42f089c8674',
    messagingSenderId: '857670497949',
    projectId: 'template-dev-d032e',
    storageBucket: 'template-dev-d032e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcBsrW4Jmzl3M_40FE4I34ViGrexZxrQA',
    appId: '1:857670497949:ios:3bba00370f4c98589c8674',
    messagingSenderId: '857670497949',
    projectId: 'template-dev-d032e',
    storageBucket: 'template-dev-d032e.appspot.com',
    iosBundleId: 'dev.akaboshinit.template.dev',
  );
}
